### ISSUE TITLE
Updates aren't running

### ISSUE THREAD

**Issue by paultag** [iancoleman/cia_world_factbook_api#10]
The latest link shows a json entry from January - https://github.com/iancoleman/cia_world_factbook_api/tree/master/data

**Comment by iancoleman** [comment]
Thanks for this.

I've been running the updates at the end of each month. I've been away from my workstation but will update at the start of next week. The updates are not automatic.

I'll also update the readme to indicate the current schedule which incorrectly says weekly.

**Comment by iancoleman** [comment]
I see that there can be 'deploy keys' set for individual repositories; I thought I could only use account keys.

Since this isolates the key security to just this repo I'll set up automatic weekly updates using a unique key for this repo.

Thanks again for prompting me to investigate this further. Makes my life easier being able to automate it.

**Comment by paultag-gov** [comment]
Oh awesome! Thanks so much, @iancoleman ! Love this project.
