### ISSUE TITLE
Config error with GOROOT variable

### ISSUE THREAD

**Issue by mjstelly** [iancoleman/cia_world_factbook_api#23]
I know nothing about Go. So I followed the instructions as best I could. I ran the executable via MacOS terminal.

I set my data folders to my project data folder like this
```
{
    "country_html_root": "~/Desktop/projects/diplomacy/app/data/country_html/pages",
    "country_html_blacklist": "~/Desktop/projects/diplomacy/app/data/country_html/blacklist",
    "country_html_yearly_summaries": "~/Desktop/projects/diplomacy/app/data/country_html/yearly_summaries",
    "country_json_root": "~/Desktop/projects/diplomacy/app/data/country_json",
    "weekly_json_root": "~/Desktop/projects/diplomacy/app/data/weekly_json"
}
```
Ran `go run parse_html_to_json.go` and immediately received the following error:
```
parse_html_to_json.go:4:2: package country is not in GOROOT (/usr/local/go/src/country)
parse_html_to_json.go:7:2: package logger is not in GOROOT (/usr/local/go/src/logger)
```
How do I resolve this error?

**Comment by iancoleman** [comment]
At the moment I can't really recommend using this project because it's out of date since the website redesign of CIA World Factbook a few years ago. I plan to update it one day but it's a big job and I don't have time to do it just now.

To answer the question though, try using GOPATH variable
`export GOPATH=$PWD`
PWD should be the path to the project and allows go to import packages from the `src` directory.

https://go.dev/doc/gopath_code
